version: "3.9"

services:
  backend:
    build: ./backend
    init: true
    container_name: partyqueue-backend
    env_file:
      - ./env/.env
    environment:
      APP_ENV: production
      DB_FILE: /app/sqlite/spotify_party_queue.sqlite3
    volumes:
      - sqlite_data:/app/sqlite
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: partyqueue-frontend
    restart: unless-stopped

  reverse-proxy:
    image: caddy:2
    container_name: partyqueue-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ./reverse-proxy/old_Caddyfile:/etc/caddy/old_Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  sqlite_data:
